[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.2.3",
    "pydantic>=2.11.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
